#!/bin/bash
#FileName  get-android.sh  
#PATH=~/bin:$PATH   
repo init -u https://android.googlesource.com/platform/manifest -b android-4.2.2_r1   
repo sync   
while [ $? = 1 ]; do   
echo "================sync failed, re-sync again ====="   
sleep 3   
repo sync   
done  
